export interface Job {
    id:string;
    alternateWorkerContact:string;
    EndDate:string;
    estimatedStartDate:string;
    approvedDate:string;
    department:number;
    description:string;
    finalDate:string;
    hiringManager:number;
    job:number;
    qty:number;
    recruiter:number;
    recruitingId:string;
    JobLocation:string;
    JobType:string;
    startDate:string;
    status:number;
    webEnabled:number;
    MicrosoftDefenderAzureBlob?:boolean;
}